(function(){"use strict";window.PRODUCT_FILTERS=(function(){let e={categories:[],priceMin:0,priceMax:1/0,search:""},n=null;function f(){const t=window.PRODUCTS_DB||[],i=new Set(t.map(r=>r.category));return Array.from(i).sort()}function u(){const t=window.PRODUCTS_DB||[];let i=1/0,r=0;return t.forEach(s=>{(s.variants||[]).forEach(c=>{c.price<i&&(i=c.price),c.price>r&&(r=c.price)})}),{min:Math.floor(i),max:Math.ceil(r)}}function v(t){return t.filter(i=>{if(e.search){const s=e.search.toLowerCase();if(s.split(/\s+/).filter(Boolean).every(function(w){return i.name.toLowerCase().includes(w)||i.category.toLowerCase().includes(w)||(i.variants||[]).some(function(c){return c.label.toLowerCase().includes(w)})})===false)return!1}if(e.categories.length>0&&!e.categories.includes(i.category))return!1;const r=g(i);return!(r<e.priceMin||r>e.priceMax)})}function g(t){return Math.min(...(t.variants||[]).map(i=>i.price))}function M(t){for(var i in t)t.hasOwnProperty(i)&&i!=="__proto__"&&i!=="constructor"&&i!=="prototype"&&(e[i]=t[i]);n&&n(o())}function o(){return{...e}}function x(){const t=u();e={categories:[],priceMin:t.min,priceMax:t.max,search:""},n&&n(o())}function h(t){n=t}function y(t){const i=f(),r=u();e.priceMax||(e.priceMin=r.min,e.priceMax=r.max),t.innerHTML=`
        <div class="filter-panel">
          <div class="filter-active-tags" id="filterActiveTags"></div>
          <div class="filter-group">
            <div class="filter-group-title">Category</div>
            <div id="filterCategories">${i.map(a=>`
              <span class="filter-chip${e.categories.includes(a)?" active":""}" data-cat="${a}">${a}</span>
            `).join("")}</div>
          </div>
          <div class="filter-group">
            <div class="filter-group-title">Price Range (N$)</div>
            <div class="filter-price-range">
              <input type="number" id="filterPriceMin" placeholder="Min" value="${e.priceMin}" min="${r.min}" max="${r.max}">
              <span>\u2014</span>
              <input type="number" id="filterPriceMax" placeholder="Max" value="${e.priceMax>=r.max?"":e.priceMax}" min="${r.min}" max="${r.max}">
            </div>
          </div>
          <button class="btn-reset-filters active" id="filterResetBtn" style="width:100%;margin-top:12px;">Clear All Filters</button>
        </div>
      `,t.querySelectorAll(".filter-chip").forEach(a=>{a.addEventListener("click",function(){const d=this.dataset.cat,m=e.categories.indexOf(d);m>=0?(e.categories.splice(m,1),this.classList.remove("active")):(e.categories.push(d),this.classList.add("active")),p(),n&&n(o())})});const s=t.querySelector("#filterPriceMin"),c=t.querySelector("#filterPriceMax");function l(){e.priceMin=parseFloat(s.value)||r.min,e.priceMax=parseFloat(c.value)||r.max,p(),n&&n(o())}s.addEventListener("change",l),c.addEventListener("change",l),t.querySelector("#filterResetBtn").addEventListener("click",function(){const a=u();e.categories=[],e.priceMin=a.min,e.priceMax=a.max,t.querySelectorAll(".filter-chip").forEach(d=>d.classList.remove("active")),s.value=a.min,c.value="",p(),n&&n(o())})}function p(){const t=document.getElementById("filterActiveTags");if(!t)return;let i="";e.categories.forEach(c=>{i+=`<span class="filter-tag">${c} <button data-remove-cat="${c}">&times;</button></span>`});const r=u();(e.priceMin>r.min||e.priceMax<r.max)&&(i+=`<span class="filter-tag">N$${e.priceMin} - N$${e.priceMax>=r.max?"\u221E":e.priceMax} <button id="removePriceFilter">&times;</button></span>`),t.innerHTML=i,t.querySelectorAll("[data-remove-cat]").forEach(c=>{c.addEventListener("click",function(){const l=this.dataset.removeCat;e.categories=e.categories.filter(a=>a!==l),document.querySelectorAll(".filter-chip").forEach(a=>{a.dataset.cat===l&&a.classList.remove("active")}),p(),n&&n(o())})});const s=t.querySelector("#removePriceFilter");s&&s.addEventListener("click",function(){const c=u();e.priceMin=c.min,e.priceMax=c.max;const l=document.getElementById("filterPriceMin"),a=document.getElementById("filterPriceMax");l&&(l.value=c.min),a&&(a.value=""),p(),n&&n(o())})}return{getCategories:f,getPriceRange:u,filter:v,setFilters:M,getActiveFilters:o,resetFilters:x,onChange:h,renderFilterPanel:y,updateActiveTags:p}})()})();
